In [37]:
# ================================================
# BOOKS SCRAPER — Complete ETL Pipeline
# Author: Suresh Kumar
# Description: Scrape books.toscrape.com,
#              transform data, save to
#              CSV/JSON and MySQL
# ================================================

import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import json
import os
from datetime import datetime
from sqlalchemy import create_engine, text
from urllib.parse import quote_plus

print("✅ All libraries imported!")
print(f"Pandas  : {pd.__version__}")
print(f"Requests: {requests.__version__}")

✅ All libraries imported!
Pandas  : 2.2.3
Requests: 2.32.3

# Cell 2 — Configuration:

In [38]:
# ── CONFIG ──
BASE_URL    = "http://books.toscrape.com/catalogue/page-{}.html"
PAGES       = 5           # pages to scrape
OUTPUT_DIR  = "output"
DB_NAME     = "books_store"  # your existing DB
TABLE_NAME  = "books"

# DB connection
password = quote_plus("Sur@#234")
engine = create_engine(
    f"mysql+mysqlconnector://root:{password}@localhost/{DB_NAME}"
)

# Rating map
RATING_MAP = {
    "One":1, "Two":2, "Three":3,
    "Four":4, "Five":5
}

os.makedirs(OUTPUT_DIR, exist_ok=True)
print("✅ Config ready!")
print(f"Scraping {PAGES} pages from books.toscrape.com")

✅ Config ready!
Scraping 5 pages from books.toscrape.com

In [39]:
r = requests.get(url)
soup = BeautifulSoup(r.text)
print(soup.prettify())

<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en-us">
 <!--<![endif]-->
 <head>
  <title>
   All products | Books to Scrape - Sandbox
  </title>
  <meta content="text/html; charset=utf-8" http-equiv="content-type"/>
  <meta content="24th Jun 2016 09:31" name="created"/>
  <meta content="" name="description"/>
  <meta content="width=device-width" name="viewport"/>
  <meta content="NOARCHIVE,NOCACHE" name="robots"/>
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
  <link href="../static/oscar/favicon.ico" rel="shortcut icon"/>
  <link href="../static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>
  <link href="../static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>
  <link href="../static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>
 </head>
 <body class="default" id="default">
  <header class="header container-fluid">
   <div class="page_inner">
    <div class="row">
     <div class="col-sm-8 h1">
      <a href="../index.html">
       Books to Scrape
      </a>
      <small>
       We love being scraped!
      </small>
     </div>
    </div>
   </div>
  </header>
  <div class="container-fluid page">
   <div class="page_inner">
    <ul class="breadcrumb">
     <li>
      <a href="../index.html">
       Home
      </a>
     </li>
     <li class="active">
      All products
     </li>
    </ul>
    <div class="row">
     <aside class="sidebar col-sm-4 col-md-3">
      <div id="promotions_left">
      </div>
      <div class="side_categories">
       <ul class="nav nav-list">
        <li>
         <a href="category/books_1/index.html">
          Books
         </a>
         <ul>
          <li>
           <a href="category/books/travel_2/index.html">
            Travel
           </a>
          </li>
          <li>
           <a href="category/books/mystery_3/index.html">
            Mystery
           </a>
          </li>
          <li>
           <a href="category/books/historical-fiction_4/index.html">
            Historical Fiction
           </a>
          </li>
          <li>
           <a href="category/books/sequential-art_5/index.html">
            Sequential Art
           </a>
          </li>
          <li>
           <a href="category/books/classics_6/index.html">
            Classics
           </a>
          </li>
          <li>
           <a href="category/books/philosophy_7/index.html">
            Philosophy
           </a>
          </li>
          <li>
           <a href="category/books/romance_8/index.html">
            Romance
           </a>
          </li>
          <li>
           <a href="category/books/womens-fiction_9/index.html">
            Womens Fiction
           </a>
          </li>
          <li>
           <a href="category/books/fiction_10/index.html">
            Fiction
           </a>
          </li>
          <li>
           <a href="category/books/childrens_11/index.html">
            Childrens
           </a>
          </li>
          <li>
           <a href="category/books/religion_12/index.html">
            Religion
           </a>
          </li>
          <li>
           <a href="category/books/nonfiction_13/index.html">
            Nonfiction
           </a>
          </li>
          <li>
           <a href="category/books/music_14/index.html">
            Music
           </a>
          </li>
          <li>
           <a href="category/books/default_15/index.html">
            Default
           </a>
          </li>
          <li>
           <a href="category/books/science-fiction_16/index.html">
            Science Fiction
           </a>
          </li>
          <li>
           <a href="category/books/sports-and-games_17/index.html">
            Sports and Games
           </a>
          </li>
          <li>
           <a href="category/books/add-a-comment_18/index.html">
            Add a comment
           </a>
          </li>
          <li>
           <a href="category/books/fantasy_19/index.html">
            Fantasy
           </a>
          </li>
          <li>
           <a href="category/books/new-adult_20/index.html">
            New Adult
           </a>
          </li>
          <li>
           <a href="category/books/young-adult_21/index.html">
            Young Adult
           </a>
          </li>
          <li>
           <a href="category/books/science_22/index.html">
            Science
           </a>
          </li>
          <li>
           <a href="category/books/poetry_23/index.html">
            Poetry
           </a>
          </li>
          <li>
           <a href="category/books/paranormal_24/index.html">
            Paranormal
           </a>
          </li>
          <li>
           <a href="category/books/art_25/index.html">
            Art
           </a>
          </li>
          <li>
           <a href="category/books/psychology_26/index.html">
            Psychology
           </a>
          </li>
          <li>
           <a href="category/books/autobiography_27/index.html">
            Autobiography
           </a>
          </li>
          <li>
           <a href="category/books/parenting_28/index.html">
            Parenting
           </a>
          </li>
          <li>
           <a href="category/books/adult-fiction_29/index.html">
            Adult Fiction
           </a>
          </li>
          <li>
           <a href="category/books/humor_30/index.html">
            Humor
           </a>
          </li>
          <li>
           <a href="category/books/horror_31/index.html">
            Horror
           </a>
          </li>
          <li>
           <a href="category/books/history_32/index.html">
            History
           </a>
          </li>
          <li>
           <a href="category/books/food-and-drink_33/index.html">
            Food and Drink
           </a>
          </li>
          <li>
           <a href="category/books/christian-fiction_34/index.html">
            Christian Fiction
           </a>
          </li>
          <li>
           <a href="category/books/business_35/index.html">
            Business
           </a>
          </li>
          <li>
           <a href="category/books/biography_36/index.html">
            Biography
           </a>
          </li>
          <li>
           <a href="category/books/thriller_37/index.html">
            Thriller
           </a>
          </li>
          <li>
           <a href="category/books/contemporary_38/index.html">
            Contemporary
           </a>
          </li>
          <li>
           <a href="category/books/spirituality_39/index.html">
            Spirituality
           </a>
          </li>
          <li>
           <a href="category/books/academic_40/index.html">
            Academic
           </a>
          </li>
          <li>
           <a href="category/books/self-help_41/index.html">
            Self Help
           </a>
          </li>
          <li>
           <a href="category/books/historical_42/index.html">
            Historical
           </a>
          </li>
          <li>
           <a href="category/books/christian_43/index.html">
            Christian
           </a>
          </li>
          <li>
           <a href="category/books/suspense_44/index.html">
            Suspense
           </a>
          </li>
          <li>
           <a href="category/books/short-stories_45/index.html">
            Short Stories
           </a>
          </li>
          <li>
           <a href="category/books/novels_46/index.html">
            Novels
           </a>
          </li>
          <li>
           <a href="category/books/health_47/index.html">
            Health
           </a>
          </li>
          <li>
           <a href="category/books/politics_48/index.html">
            Politics
           </a>
          </li>
          <li>
           <a href="category/books/cultural_49/index.html">
            Cultural
           </a>
          </li>
          <li>
           <a href="category/books/erotica_50/index.html">
            Erotica
           </a>
          </li>
          <li>
           <a href="category/books/crime_51/index.html">
            Crime
           </a>
          </li>
         </ul>
        </li>
       </ul>
      </div>
     </aside>
     <div class="col-sm-8 col-md-9">
      <div class="page-header action">
       <h1>
        All products
       </h1>
      </div>
      <div id="messages">
      </div>
      <div id="promotions">
      </div>
      <form class="form-horizontal" method="get">
       <div style="display:none">
       </div>
       <strong>
        1000
       </strong>
       results - showing
       <strong>
        81
       </strong>
       to
       <strong>
        100
       </strong>
       .
      </form>
      <section>
       <div class="alert alert-warning" role="alert">
        <strong>
         Warning!
        </strong>
        This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.
       </div>
       <div>
        <ol class="row">
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="princess-jellyfish-2-in-1-omnibus-vol-01-princess-jellyfish-2-in-1-omnibus-1_920/index.html">
             <img alt="Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Princess Jellyfish 2-in-1 Omnibus #1)" class="thumbnail" src="../media/cache/78/0b/780b2c28122750c2c383846155815bf7.jpg"/>
            </a>
           </div>
           <p class="star-rating Five">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="princess-jellyfish-2-in-1-omnibus-vol-01-princess-jellyfish-2-in-1-omnibus-1_920/index.html" title="Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Princess Jellyfish 2-in-1 Omnibus #1)">
             Princess Jellyfish 2-in-1 Omnibus, ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£13.61
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="princess-between-worlds-wide-awake-princess-5_919/index.html">
             <img alt="Princess Between Worlds (Wide-Awake Princess #5)" class="thumbnail" src="../media/cache/b7/e8/b7e84b78be3d9bb79b71156a5e5d4e42.jpg"/>
            </a>
           </div>
           <p class="star-rating Five">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="princess-between-worlds-wide-awake-princess-5_919/index.html" title="Princess Between Worlds (Wide-Awake Princess #5)">
             Princess Between Worlds (Wide-Awake ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£13.34
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="pop-gun-war-volume-1-gift_918/index.html">
             <img alt="Pop Gun War, Volume 1: Gift" class="thumbnail" src="../media/cache/c8/2f/c82f629a31b3f47bdb17ac14aa51076d.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="pop-gun-war-volume-1-gift_918/index.html" title="Pop Gun War, Volume 1: Gift">
             Pop Gun War, Volume ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£18.97
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="political-suicide-missteps-peccadilloes-bad-calls-backroom-hijinx-sordid-pasts-rotten-breaks-and-just-plain-dumb-mistakes-in-the-annals-of-american-politics_917/index.html">
             <img alt="Political Suicide: Missteps, Peccadilloes, Bad Calls, Backroom Hijinx, Sordid Pasts, Rotten Breaks, and Just Plain Dumb Mistakes in the Annals of American Politics" class="thumbnail" src="../media/cache/64/44/6444dacdcb9edaadbbd691524622aeb8.jpg"/>
            </a>
           </div>
           <p class="star-rating Two">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="political-suicide-missteps-peccadilloes-bad-calls-backroom-hijinx-sordid-pasts-rotten-breaks-and-just-plain-dumb-mistakes-in-the-annals-of-american-politics_917/index.html" title="Political Suicide: Missteps, Peccadilloes, Bad Calls, Backroom Hijinx, Sordid Pasts, Rotten Breaks, and Just Plain Dumb Mistakes in the Annals of American Politics">
             Political Suicide: Missteps, Peccadilloes, ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£36.28
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="patience_916/index.html">
             <img alt="Patience" class="thumbnail" src="../media/cache/01/72/01726c619a05114dca75bd840095016d.jpg"/>
            </a>
           </div>
           <p class="star-rating Three">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="patience_916/index.html" title="Patience">
             Patience
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£10.16
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="outcast-vol-1-a-darkness-surrounds-him-outcast-1_915/index.html">
             <img alt="Outcast, Vol. 1: A Darkness Surrounds Him (Outcast #1)" class="thumbnail" src="../media/cache/cb/00/cb004189f548d75ad430d3ed19e6daa9.jpg"/>
            </a>
           </div>
           <p class="star-rating Four">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="outcast-vol-1-a-darkness-surrounds-him-outcast-1_915/index.html" title="Outcast, Vol. 1: A Darkness Surrounds Him (Outcast #1)">
             Outcast, Vol. 1: A ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£15.44
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="orange-the-complete-collection-1-orange-the-complete-collection-1_914/index.html">
             <img alt="orange: The Complete Collection 1 (orange: The Complete Collection #1)" class="thumbnail" src="../media/cache/03/88/03886a8502ca54dbce0d91c2568ab69d.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="orange-the-complete-collection-1-orange-the-complete-collection-1_914/index.html" title="orange: The Complete Collection 1 (orange: The Complete Collection #1)">
             orange: The Complete Collection ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£48.41
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket

# Cell 3 — Scraping Functions:

In [40]:
def fetch_page(url):
    """
    Fetch and parse one page
    Returns: BeautifulSoup object or None
    """
    try:
        response = requests.get(url)
        response.raise_for_status()
        return BeautifulSoup(response.text,"html.parser")
    except requests.exceptions.ConnectionError:
        print(f"Connection error: {url}")
        return None
    except requests.exceptions.Timeout:
        print(f"Timeout: {url}")
        return None
    except Exception as e:
        print(f"From fetch_url function Error: {e}")

In [41]:
def extract_books(soup, page_num):
    """ 
    Extract all books from one page
    Returns: list of dicts
    """
    books = []
    articles = soup.find_all("article", class_="product_pod")

    for book in articles:
        try:
            title = book.find("h3").find("a")["title"]
            price = float(
                book.find("p", class_="price_color")
                .text.replace("£","")
                .replace("Â","")
                .strip()
            )
            rating_word = book.find("p",class_="star-rating")["class"][1]
            rating = RATING_MAP.get(rating_word,0)

            availability = book.find(
                 "p", class_="instock availability"
            ).text.strip()

            books.append(
                {
                    "title": title,
                    "price_gbp":price,
                    "rating":rating,
                    "availability": availability,
                    "page": page_num,
                    "scraped_at": datetime.now().strftime(
                        "%Y-%m-%d %H:%M:%S"
                    )
                }
            )
        except Exception as e:
            print(f"Skipped one book: {e}")
            continue
    return books

def get_total_pages(soup):
    """Get total pages available"""
    pager = soup.find("li", class_="current")
    if pager:
        return int(
            pager.text.strip().split("of")[1].strip()
        )
    return 1

print("✅ Scraping functions ready!")

✅ Scraping functions ready!

# Extract

In [42]:
print("="*50)
print(" STEP 1: EXTRACT - Scraping Books")
print("="*50)

all_books = []

for page in range(1, PAGES+1):
    url = BASE_URL.format(page)
    soup = fetch_page(url)

    if soup:
        books = extract_books(soup,page)
        all_books.extend(books)
        print(f"Page {page}/{PAGES}:"
              F"{len(books)} books scraped")
    else:
        print(f"Page {page} failed!")

print(f"Total extracted: {len(all_books)} books")

==================================================
 STEP 1: EXTRACT - Scraping Books
==================================================
Page 1/5:20 books scraped
Page 2/5:20 books scraped
Page 3/5:20 books scraped
Page 4/5:20 books scraped
Page 5/5:20 books scraped
Total extracted: 100 books

# Load into DataFrame

In [43]:
df_raw = pd.DataFrame(all_books)
print(f"Shape: {df_raw.shape}")
df_raw.head()

Shape: (100, 6)

,title,price_gbp,rating,availability,page,scraped_at
0,A Light in the Attic,51.77,3,In stock,1,2026-09-27 00:04:29
1,Tipping the Velvet,53.74,1,In stock,1,2026-09-27 00:04:29
2,Soumission,50.10,1,In stock,1,2026-09-27 00:04:29
3,Sharp Objects,47.82,4,In stock,1,2026-09-27 00:04:29
4,Sapiens: A Brief History of Humankind,54.23,5,In stock,1,2026-09-27 00:04:29

# Transform

In [45]:
print("=" * 50)
print(" STEP 2: TRANSFORM - Clean & Enrich")
print("=" * 50)

df = df_raw.copy()

# 1 Check missing values
print(f"Missing values: {df.isnull().sum()}")

# 2 Add price category using np.where
df["price_category"] = np.where(
    df["price_gbp"] > 40, "Expensive",
    np.where(
        df["price_gbp"] > 20, "Medium","Affordable"
    )
)

# 3 Add rating label
df["rating_label"] = np.where(
    df["rating"] == 5, "Excellent",
    np.where(
        df["rating"]>=3, "Good","Poor"
    )
)

# 4 Add in_stock flage
df["in_stock"] = np.where(
    df["availability"] == "In stock", 1,0
)

# 5 Add price in INR
df["price_inr"] = (df["price_gbp"]*106).round(2)

# 6 Add recommendation flag
df["recommended"] = np.where(
    (df["rating"]>= 4) &
    (df["price_gbp"]<20) &
    (df["in_stock"] ==1), "Yes","No"
)

# 7. Clean title — remove extra spaces
df["title"] = df["title"].str.strip()

print("\n✅ Transformations complete!")
print(f"\nNew columns added:")
print(df.columns.tolist())
df.head()

==================================================
 STEP 2: TRANSFORM - Clean & Enrich
==================================================
Missing values: title           0
price_gbp       0
rating          0
availability    0
page            0
scraped_at      0
dtype: int64

✅ Transformations complete!

New columns added:
['title', 'price_gbp', 'rating', 'availability', 'page', 'scraped_at', 'price_category', 'rating_label', 'in_stock', 'price_inr', 'recommended']

,title,price_gbp,rating,availability,page,scraped_at,price_category,rating_label,in_stock,price_inr,recommended
0,A Light in the Attic,51.77,3,In stock,1,2026-09-27 00:04:29,Expensive,Good,1,5487.62,No
1,Tipping the Velvet,53.74,1,In stock,1,2026-09-27 00:04:29,Expensive,Poor,1,5696.44,No
2,Soumission,50.10,1,In stock,1,2026-09-27 00:04:29,Expensive,Poor,1,5310.60,No
3,Sharp Objects,47.82,4,In stock,1,2026-09-27 00:04:29,Expensive,Good,1,5068.92,No
4,Sapiens: A Brief History of Humankind,54.23,5,In stock,1,2026-09-27 00:04:29,Expensive,Excellent,1,5748.38,No

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           100 non-null    object
 1   price_gbp       100 non-null    float64
 2   rating          100 non-null    int64
 3   availability    100 non-null    object
 4   page            100 non-null    int64
 5   scraped_at      100 non-null    object
 6   price_category  100 non-null    object
 7   rating_label    100 non-null    object
 8   in_stock        100 non-null    int64
 9   price_inr       100 non-null    float64
 10  recommended     100 non-null    object
dtypes: float64(2), int64(3), object(6)
memory usage: 8.7+ KB

# Analysis

In [57]:
print("=" * 50)
print("   STEP 3: ANALYSIS")
print("=" * 50)

print(f"Total Books: {len(df)}")
print(f"Pages Scraped: {PAGES}")
print(f"In Stock: {(df["in_stock"]).sum()}")
print(f"Out of Stock: {(df["in_stock"]==0).sum()}")

print(f"\nPRICE ANALYSIS:")
print(f"Avg price (GBP) : £{df['price_gbp'].mean():.2f}")
print(f"Max price (GBP) : £{df['price_gbp'].max():.2f}")
print(f"Min price (GBP) : £{df['price_gbp'].min():.2f}")
print(f"Avg price (INR) : ₹{df['price_inr'].mean():.2f}")

print(f"\nRATING ANALYSIS:")
print(df["rating"].value_counts().sort_index())

print(f"\nPRICE CATEGORY:")
print(df["price_category"].value_counts())

print("\n RECOMMENDED BOOKS:")
recommended = df[df["recommended"] =="Yes"]
print(recommended[["title","price_inr","rating"]].head())

==================================================
   STEP 3: ANALYSIS
==================================================
Total Books: 100
Pages Scraped: 5
In Stock: 100
Out of Stock: 0

PRICE ANALYSIS:
Avg price (GBP) : £34.56
Max price (GBP) : £58.11
Min price (GBP) : £10.16
Avg price (INR) : ₹3663.43

RATING ANALYSIS:
rating
1    22
2    19
3    22
4    18
5    19
Name: count, dtype: int64

PRICE CATEGORY:
price_category
Expensive     40
Medium        34
Affordable    26
Name: count, dtype: int64

 RECOMMENDED BOOKS:
                                                title  price_inr  rating
12                                        Set Me Free    1850.76       5
30  The Four Agreements: A Practical Guide to Pers...    1871.96       5
34                                     Sophie's World    1689.64       5
47            Untitled Collection: Sabbath Poems 2014    1512.62       4
53                                    This One Summer    2065.94       4

In [59]:
print(f"\nGROUPBY — Rating vs Avg Price:")

analysis = df.groupby("rating").agg(
    count = ("title","count"),
    avg_price = ("price_gbp","mean"),
    min_price = ("price_gbp","min"),
    max_price = ("price_gbp","max")
).round(2)
analysis

GROUPBY — Rating vs Avg Price:

        count  avg_price  min_price  max_price
rating
1          22      35.52      12.84      56.41
2          19      35.91      13.99      56.40
3          22      36.84      10.16      57.31
4          18      33.98      14.02      58.11
5          19      30.01      13.34      54.23

# Load to Files

In [60]:
print("=" * 50)
print("   STEP 4: LOAD — Save Files")
print("=" * 50)

df.to_csv(
    f"{OUTPUT_DIR}/books_full.csv",
    index=False
)

print("Saved: books_full.csv")

df.to_json(
    f"{OUTPUT_DIR}/books_full.json",
    orient="records",
    indent=4
)
print("Saved: books_full.json")

#Save Recommended only
recommended = df[df["recommended"]=="Yes"]
recommended.to_csv(
    f"{OUTPUT_DIR}/books_recommended.csv",
    index = False
)

# Summary report
summary = {
    "scraped_at":     datetime.now().strftime(
                      "%Y-%m-%d %H:%M"),
    "pages_scraped":  PAGES,
    "total_books":    int(len(df)),
    "in_stock":       int(df["in_stock"].sum()),
    "avg_price_gbp":  float(df["price_gbp"].mean().round(2)),
    "avg_price_inr":  float(df["price_inr"].mean().round(2)),
    "avg_rating":     float(df["rating"].mean().round(1)),
    "recommended":    int(len(recommended)),
    "price_categories": {
        "Affordable": int((df["price_category"]=="Affordable").sum()),
        "Medium":     int((df["price_category"]=="Medium").sum()),
        "Expensive":  int((df["price_category"]=="Expensive").sum())
    },
    "ratings": {
        str(i): int((df["rating"]==i).sum())
        for i in range(1,6)
    }
}

with open(f"{OUTPUT_DIR}/summary_report.json","w") as f:
    json.dump(summary, f, indent=4)
print("✅ Saved: summary_report.json")

print(f"\n{json.dumps(summary, indent=4)}")

==================================================
   STEP 4: LOAD — Save Files
==================================================
Saved: books_full.csv
Saved: books_full.json
✅ Saved: summary_report.json

{
    "scraped_at": "2026-09-27 01:17",
    "pages_scraped": 5,
    "total_books": 100,
    "in_stock": 100,
    "avg_price_gbp": 34.56,
    "avg_price_inr": 3663.43,
    "avg_rating": 2.9,
    "recommended": 10,
    "price_categories": {
        "Affordable": 26,
        "Medium": 34,
        "Expensive": 40
    },
    "ratings": {
        "1": 22,
        "2": 19,
        "3": 22,
        "4": 18,
        "5": 19
    }
}

# Load to MySQL

In [62]:
print("=" * 50)
print("   STEP 5: LOAD — Save to MySQL")
print("=" * 50)

try:
    df.to_sql(
        TABLE_NAME,
        engine,
        if_exists="replace",
        index=False
    )
    print(f"Saved {len(df)} rows to MySQL")

    df_verify = pd.read_sql(
        f"SELECT COUNT(*) as total FROM {TABLE_NAME}",
        engine
    )

    print(f"Verified: {df_verify['total'][0]} rows in DB!")

    df_top = pd.read_sql("""
        SELECT title, price_gbp,
               rating, price_category
        FROM books
        WHERE rating = 5
        ORDER BY price_gbp ASC
        LIMIT 5
    """, engine)
    print(f"\nTop 5 rated cheapest books:")
    print(df_top)

except Exception as e:
    print(f"DB Error: {e}")
    print("Data saved to CSV/JSON ✅")

==================================================
   STEP 5: LOAD — Save to MySQL
==================================================
Saved 100 rows to MySQL
Verified: 100 rows in DB!

Top 5 rated cheapest books:
                                               title  price_gbp  rating  \
0   Princess Between Worlds (Wide-Awake Princess #5)      13.34       5
1  Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Pr...      13.61       5
2                                     Sophie's World      15.94       5
3                                             Thirst      17.27       5
4                                        Set Me Free      17.46       5

  price_category
0     Affordable
1     Affordable
2     Affordable
3     Affordable
4     Affordable

# Final Summary

In [63]:
print("\n" + "=" * 50)
print("PIPELINE COMPLETE!")
print("=" * 50)
print(f"""
Books Scraper — ETL Pipeline Summary
─────────────────────────────────────
Pages Scraped  : {PAGES}
Total Books    : {len(df)}
In Stock       : {df['in_stock'].sum()}
Recommended    : {len(df[df['recommended']=='Yes'])}

💰 Price Stats:
Avg Price (GBP): £{df['price_gbp'].mean():.2f}
Avg Price (INR): ₹{df['price_inr'].mean():.2f}

⭐ Rating Stats:
Avg Rating     : {df['rating'].mean():.1f} / 5.0
5-Star Books   : {(df['rating']==5).sum()}

📁 Output Files:
✅ output/books_full.csv
✅ output/books_full.json
✅ output/books_recommended.csv
✅ output/summary_report.json
✅ MySQL table: books
─────────────────────────────────────
""")

==================================================
PIPELINE COMPLETE!
==================================================

Books Scraper — ETL Pipeline Summary
─────────────────────────────────────
Pages Scraped  : 5
Total Books    : 100
In Stock       : 100
Recommended    : 10

💰 Price Stats:
Avg Price (GBP): £34.56
Avg Price (INR): ₹3663.43

⭐ Rating Stats:
Avg Rating     : 2.9 / 5.0
5-Star Books   : 19

📁 Output Files:
✅ output/books_full.csv
✅ output/books_full.json
✅ output/books_recommended.csv
✅ output/summary_report.json
✅ MySQL table: books
─────────────────────────────────────