In [2]:
import pandas as pd
import numpy as np

In [20]:
raw = pd.DataFrame({
    "emp_id":     ["E001","E002","E003","E004","E005","E006"],
    "name":       ["Suresh","Raj",None,"Priya","Ankit","Sneha"],
    "department": ["Operations","IT","HR","IT","Operations",None],
    "salary":     [48000, 62000, 45000, None, 71000, 38000],
    "status":     ["Active","Active","Inactive","?","Active","Active"]
})
raw

  emp_id    name  department   salary    status
0   E001  Suresh  Operations  48000.0    Active
1   E002     Raj          IT  62000.0    Active
2   E003    None          HR  45000.0  Inactive
3   E004   Priya          IT      NaN         ?
4   E005   Ankit  Operations  71000.0    Active
5   E006   Sneha        None  38000.0    Active

In [21]:
# Replacing ? in status with NaN
raw["status"] = raw["status"].replace("?", np.nan)
raw

  emp_id    name  department   salary    status
0   E001  Suresh  Operations  48000.0    Active
1   E002     Raj          IT  62000.0    Active
2   E003    None          HR  45000.0  Inactive
3   E004   Priya          IT      NaN       NaN
4   E005   Ankit  Operations  71000.0    Active
5   E006   Sneha        None  38000.0    Active

In [23]:
# Droping rows where name is missing
raw = raw.dropna(subset =["name"])
raw

  emp_id    name  department   salary  status
0   E001  Suresh  Operations  48000.0  Active
1   E002     Raj          IT  62000.0  Active
3   E004   Priya          IT      NaN     NaN
4   E005   Ankit  Operations  71000.0  Active
5   E006   Sneha        None  38000.0  Active

In [25]:
# Fill missing salary with department mean
raw["salary"] = raw.groupby("department")["salary"].transform(lambda x: x.fillna(x.mean()))
raw

  emp_id    name  department   salary  status
0   E001  Suresh  Operations  48000.0  Active
1   E002     Raj          IT  62000.0  Active
3   E004   Priya          IT  62000.0     NaN
4   E005   Ankit  Operations  71000.0  Active
5   E006   Sneha        None      NaN  Active

In [26]:
# Fill missing department with unknown
raw["department"] = raw["department"].fillna("Unknown")
raw

  emp_id    name  department   salary  status
0   E001  Suresh  Operations  48000.0  Active
1   E002     Raj          IT  62000.0  Active
3   E004   Priya          IT  62000.0     NaN
4   E005   Ankit  Operations  71000.0  Active
5   E006   Sneha     Unknown      NaN  Active

In [27]:
# fill missing salary with overall mean (E006 has no department)
raw["salary"] = raw["salary"].fillna(raw["salary"].mean())
raw

  emp_id    name  department   salary  status
0   E001  Suresh  Operations  48000.0  Active
1   E002     Raj          IT  62000.0  Active
3   E004   Priya          IT  62000.0     NaN
4   E005   Ankit  Operations  71000.0  Active
5   E006   Sneha     Unknown  60750.0  Active

In [31]:
# Fill missing status with mode
raw["status"] = raw["status"].fillna(raw["status"].mode()[0])
print(raw)

  emp_id    name  department   salary  status
0   E001  Suresh  Operations  48000.0  Active
1   E002     Raj          IT  62000.0  Active
3   E004   Priya          IT  62000.0  Active
4   E005   Ankit  Operations  71000.0  Active
5   E006   Sneha     Unknown  60750.0  Active

In [32]:
# Add hike_salary — 10% hike for Active, 0% for Inactive

raw["hike_salary"] = np.where(
    raw["status"] == "Active",
    raw["salary"] * 1.1,   # 10% hike if Active
    raw["salary"] * 1.0    # 0% hike if Inactive
)
raw

  emp_id    name  department   salary  status  hike_salary
0   E001  Suresh  Operations  48000.0  Active      52800.0
1   E002     Raj          IT  62000.0  Active      68200.0
3   E004   Priya          IT  62000.0  Active      68200.0
4   E005   Ankit  Operations  71000.0  Active      78100.0
5   E006   Sneha     Unknown  60750.0  Active      66825.0

In [33]:
# Add annual_bonus — 5% of salary for IT dept, 3% for others
raw["annual_bonus"] = np.where(
    raw["department"] == "IT",
    raw["salary"]*0.05,
    raw["salary"]*0.03)
raw

  emp_id    name  department   salary  status  hike_salary  annual_bonus
0   E001  Suresh  Operations  48000.0  Active      52800.0        1440.0
1   E002     Raj          IT  62000.0  Active      68200.0        3100.0
3   E004   Priya          IT  62000.0  Active      68200.0        3100.0
4   E005   Ankit  Operations  71000.0  Active      78100.0        2130.0
5   E006   Sneha     Unknown  60750.0  Active      66825.0        1822.5

In [36]:
# GroupBy department — show avg salary and count

summary = raw.groupby("department")["salary"].agg(["mean","count"])
summary

               mean  count
department
IT          62000.0      2
Operations  59500.0      2
Unknown     60750.0      1

In [37]:
# save cleaned data to CSV
raw.to_csv("employee_report.csv", index=False)
print("CSV Saved!")

CSV Saved!

In [38]:
# Saving summary to JSON
import json

summary_dict = summary.to_dict()
with open("summary_report.json","w") as f:
    json.dump(summary_dict, f, indent=4)
print("JSON Saved")

JSON Saved