In [42]:
import pandas as pd
import datetime as dt

In [2]:
rev = {
    "revenue":["20$","50$","150$","100$"]
}
df = pd.DataFrame(rev)

In [3]:
df.sum()

revenue    20$50$150$100$
dtype: object

1. Problem:  Above revenue in the string formate with $. so if we sum we wont get correct total revenue.
2. Solution: we need to remove the $ symbol and convert into integer

In [5]:
df['revenue'] = df['revenue'].str.strip('$')
df

  revenue
0      20
1      50
2     150
3     100

In [6]:
# Converting into integer type using astype() method
df['revenue'] = df['revenue'].astype('int')
assert df['revenue'].dtype == ('int')
df.dtypes

revenue    int64
dtype: object

In [13]:
df.describe().round(2)

       revenue
count     4.00
mean     80.00
std      57.15
min      20.00
25%      42.50
50%      75.00
75%     112.50
max     150.00

## Numerical or Categorical

In [7]:
# 0. Never married, 1. married, 2. separated, 3. divorced
marriage = {
    'marriage_status':[2,1,3,0,1,2,2]
}
df = pd.DataFrame(marriage)
df

   marriage_status
0                2
1                1
2                3
3                0
4                1
5                2
6                2

In [8]:
# Above data is categorical if we do describe it shows the sum,mean,max but its worng no use of stats because its categorial data
df.describe()

       marriage_status
count         7.000000
mean          1.571429
std           0.975900
min           0.000000
25%           1.000000
50%           2.000000
75%           2.000000
max           3.000000

In [18]:
# So we need to convert into catogry type to get accurate and good quality results
df['marriage_status'] = df["marriage_status"].astype('category')
df.describe()

        marriage_status
count                 7
unique                4
top                   2
freq                  3