## Duplicates

Suppose the user entered the first , last name,address, height and weight later he entered again to change his height so duplicate rows formed to handle this we use duplicated() method

In [3]:
import pandas as pd

data = {
    "first_name": ["Justin", "Justin", "Sarah", "Michael", "Sarah", "David"],
    "last_name": ["Saddlemyer", "Saddlemyer", "Connor", "Smith", "Connor", "Johnson"],
    "address": [
        "Boulevard du Jardin Botanique 3, Bruxelles",
        "Boulevard du Jardin Botanique 3, Bruxelles",
        "Baker Street 221B, London",
        "Wall Street 50, New York",
        "Baker Street 221B, London",
        "Park Avenue 12, Chicago"
    ],
    "height": ["193 cm", "194 cm", "168 cm", "175 cm", "168 cm", "182 cm"],
    "weight": ["87 kg", "87 kg", "55 kg", "70 kg", "55 kg", "78 kg"]
}

df = pd.DataFrame(data)
df

,first_name,last_name,address,height,weight
0,Justin,Saddlemyer,"Boulevard du Jardin Botanique 3, Bruxelles",193 cm,87 kg
1,Justin,Saddlemyer,"Boulevard du Jardin Botanique 3, Bruxelles",194 cm,87 kg
2,Sarah,Connor,"Baker Street 221B, London",168 cm,55 kg
3,Michael,Smith,"Wall Street 50, New York",175 cm,70 kg
4,Sarah,Connor,"Baker Street 221B, London",168 cm,55 kg
5,David,Johnson,"Park Avenue 12, Chicago",182 cm,78 kg

In [12]:
columns = ['first_name','last_name','address']
duplicates = df.duplicated(subset=columns, keep=False)

In [10]:
df[duplicates]

,first_name,last_name,address,height,weight
0,Justin,Saddlemyer,"Boulevard du Jardin Botanique 3, Bruxelles",193 cm,87 kg
1,Justin,Saddlemyer,"Boulevard du Jardin Botanique 3, Bruxelles",194 cm,87 kg
2,Sarah,Connor,"Baker Street 221B, London",168 cm,55 kg
4,Sarah,Connor,"Baker Street 221B, London",168 cm,55 kg

In [13]:
# Droping duplicates only
df.drop_duplicates(inplace=True)
df

,first_name,last_name,address,height,weight
0,Justin,Saddlemyer,"Boulevard du Jardin Botanique 3, Bruxelles",193 cm,87 kg
1,Justin,Saddlemyer,"Boulevard du Jardin Botanique 3, Bruxelles",194 cm,87 kg
2,Sarah,Connor,"Baker Street 221B, London",168 cm,55 kg
3,Michael,Smith,"Wall Street 50, New York",175 cm,70 kg
5,David,Johnson,"Park Avenue 12, Chicago",182 cm,78 kg